# yazi.toml

[manager]
ratio = [0, 4, 0]

[opener]
# yazelix v4
edit = [
  { run = '~/.config/yazi/open_file.sh $1', desc = "Open File in a new pane" },
]

# yazelix v3
# edit = [
#   { run = 'zellij edit "$1"', desc = "Open File in a new pane" }
# ]
