# Get editor completions based on config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Insert blank line between prompts
add_newline = true

format = """
$directory\
$username\
$git_branch\
$git_status\
$git_commit\
$git_state\
$python\
$line_break\
$character"""

#$directory\ Unsure if I want to add this to my format...

[character]
success_symbol = '[ ](bold green)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = 'bold blue'
truncation_length = 16
truncation_symbol = '...'

[python]
symbol = ' '
version_format = '${major}.${minor}.${patch}'
style = 'yellow bold'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[directory]
truncation_length = 1
format = '[$path]($style) '


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

pallete = "catppuccin_mocha"
