theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
auto-save = false
undercurl = true
completion-timeout = 5
completion-trigger-len = 1

[editor.indent-guides]
render = true

[keys.normal."space"]
n = ":sh ~/.config/helix/open-yazi-picker.sh"
