[language-server.djlsp]
command = "djlsp"

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.pylsp.config.pylsp.plugins]
jedi = { environment = "env" }
flake8 = { enabled = true, maxLineLength = 88 }
rope_autoimport = { enabled = false }
autopep8 = { enabled = false }
mccabe = { enabled = false }
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
pylint = { enabled = false }
yapf = { enabled = false }
ruff = { enabled = false }
pylsp_mypy = { enabled = false }

[[language]]
name = "htmldjango"
scope = "source.htmldjango"
injection-regex = "htmldjango"
roots = []
file-types = [ "html" ]
indent = { tab-width = 2, unit = "  " }
language-servers = [ "djlsp", "vscode-html-language-server" ]

[language.auto-pairs]
'"' = '"'
'(' = ')'
'[' = ']'
'{' = '}'
'%' = '%'
'<' = '>'

[[grammar]]
name = "htmldjango"
source = { git = "https://github.com/interdependence/tree-sitter-htmldjango" , rev = "ea71012d3fe14dd0b69f36be4f96bdfe9155ebae" }

[[language]]
name = "sql"
language-servers = ["sql-language-server"]
formatter = { command = "sqlfluff", args = ["format", "--dialect", "postgres", "-"] }
