# OLD
# [[language]]
# name = "python"
# scope = "source.python"
# injection-regex = "python"
# file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
# shebangs = ["python"]
# roots = [".", "pyproject.toml", "pyrightconfig.json"]
# comment-token = "#"
# language-servers = ["pyright", "ruff"]
# indent = { tab-width = 4, unit = "    " }

# [language-server.pyright]
# command = "pyright-langserver"
# args = ["--stdio"]

# [language-server.pyright.config]
# reportMissingTypeStubs = false

# [language-server.pyright.config.python.analysis]
# typeCheckingMode = "basic"

# [language-server.ruff]
# command = "ruff-lsp"

# [language-server.ruff.config]
# settings = {args = []}

# [language-server.djlsp]
# command = "djlsp"

# [[language]]
# name = "htmldjango"
# scope = "source.htmldjango"
# injection-regex = "htmldjango"
# roots = []
# file-types = [ "html" ]
# indent = { tab-width = 2, unit = " " }
# language-servers = [ "djlsp", "vscode-html-language-server" ]

# [[grammar]]
# name = "htmldjango"
# source = { git = "https://github.com/interdependence/tree-sitter-htmldjango" , rev = "ea71012d3fe14dd0b69f36be4f96bdfe9155ebae" }

[language-server.djlsp]
command = "djlsp"

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.pylsp.config.pylsp.plugins]
jedi = {environment = "env"}
flake8 = {enabled = true, maxLineLength = 88}
# Disable rope_autimport, make startup slow and invalid import path for env variable 
#rope_autoimport = {enabled = true, memory=true}
rope_autoimport = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = true}

[[language]]
name = "htmldjango"
scope = "source.htmldjango"
injection-regex = "htmldjango"
roots = []
file-types = [ "html" ]
indent = { tab-width = 2, unit = "  " }
language-servers = [ "djlsp", "vscode-html-language-server" ]

[language.auto-pairs]
'"' = '"'
'(' = ')'
'[' = ']'
'{' = '}'
'%' = '%'
'<' = '>'

[[grammar]]
name = "htmldjango"
source = { git = "https://github.com/interdependence/tree-sitter-htmldjango" , rev = "ea71012d3fe14dd0b69f36be4f96bdfe9155ebae" }

[[language]]
name = "sql"
language-servers = ["sql-language-server"]
formatter = { command = "sqlfluff", args = ["format", "--dialect", "postgres", "-"] }
